# Generated by Django 6.0.4 on 2026-05-02 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherverificationdocument',
            options={'ordering': ['-created_at'], 'verbose_name': 'Öğretmen doğrulama belgesi', 'verbose_name_plural': 'Öğretmen doğrulama belgeleri'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Kullanıcı', 'verbose_name_plural': 'Kullanıcılar'},
        ),
    ]
