# Generated by Django 6.0.4 on 2026-05-02 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_meta_verbose_tr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherverificationdocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yükleme zamanı'),
        ),
        migrations.AlterField(
            model_name='teacherverificationdocument',
            name='file',
            field=models.FileField(help_text='Kimlik, diploma veya benzeri doğrulama evrakı.', upload_to='teacher-docs/%Y/%m/', verbose_name='Belge dosyası'),
        ),
        migrations.AlterField(
            model_name='teacherverificationdocument',
            name='original_filename',
            field=models.CharField(blank=True, default='', help_text='Yükleme sırasında tarayıcıdan gelen ad (isteğe bağlı).', max_length=255, verbose_name='Orijinal dosya adı'),
        ),
        migrations.AlterField(
            model_name='teacherverificationdocument',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_documents', to=settings.AUTH_USER_MODEL, verbose_name='Öğretmen'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, default='', help_text='Harici barındırılan profil fotoğrafı bağlantısı.', verbose_name='Profil görseli URL'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='Profilde görünebilecek kısa tanıtım.', verbose_name='Biyografi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('teacher', 'Öğretmen'), ('student', 'Öğrenci')], default='student', help_text='Öğretmen mi öğrenci mi olduğunu belirtir.', max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='user',
            name='teacher_verification_status',
            field=models.CharField(choices=[('not_required', 'Gerekmez'), ('pending', 'Beklemede'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], default='not_required', help_text='Öğretmen profili için belge inceleme sürecinin durumu.', max_length=20, verbose_name='Öğretmen doğrulama durumu'),
        ),
        migrations.AlterField(
            model_name='user',
            name='teacher_verified_at',
            field=models.DateTimeField(blank=True, help_text='Onaylandığında admin tarafından işaretlenebilir.', null=True, verbose_name='Doğrulama onay zamanı'),
        ),
    ]
