# Generated by Django 6.0.4 on 2026-05-02 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_lesson_is_preview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at'], 'verbose_name': 'Kurs', 'verbose_name_plural': 'Kurslar'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order_index', 'id'], 'verbose_name': 'Ders', 'verbose_name_plural': 'Dersler'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['title'], 'verbose_name': 'Branş / konu', 'verbose_name_plural': 'Branşlar / konular'},
        ),
    ]
