# Generated by Django 6.0.4 on 2026-05-02 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_uniq_constraints_and_meta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='access_level',
            field=models.CharField(choices=[('free', 'Ücretsiz'), ('basic', 'Temel'), ('pro', 'Pro'), ('enterprise', 'Kurumsal')], default='free', help_text='Abonelik veya kilitleme kuralları için etiket.', max_length=20, verbose_name='Erişim seviyesi'),
        ),
        migrations.AlterField(
            model_name='course',
            name='cover_image_url',
            field=models.URLField(blank=True, default='', help_text='Liste ve detayda görünecek kapak görseli.', verbose_name='Kapak görseli URL'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_published',
            field=models.BooleanField(default=False, help_text='İşaretli değilse herkese açık liste dışına alınır.', verbose_name='Yayında'),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='lessons.subject', verbose_name='Branş'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(help_text='Bu kursu oluşturan kullanıcı.', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='Eğitmen'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=180, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True, default='', help_text='Markdown veya düz metin ders içeriği.', verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lessons.course', verbose_name='Kurs'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=45, help_text='Öğrenme süresinin tahmini uzunluğu.', verbose_name='Süre (dakika)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='is_preview',
            field=models.BooleanField(default=False, help_text='Üyeliğe bağlı olmadan görülebilecek kısa içerik.', verbose_name='Ön izleme'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Yayında'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order_index',
            field=models.PositiveIntegerField(default=0, help_text='Çalma/liste sırası (küçük önce gelir).', verbose_name='Sıra'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='price_try',
            field=models.PositiveIntegerField(default=0, help_text='Ücretli içerikler için Türk Lirası.', verbose_name='Fiyat (₺)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=180, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, default='', help_text='İsteğe bağlı uzaktan içerik adresi.', verbose_name='Video URL'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Kısa ad (slug)'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Başlık'),
        ),
    ]
