# Generated by Django 6.0.4 on 2026-04-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("location", models.CharField(blank=True, default="", max_length=180)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("cover_image_url", models.URLField(blank=True, default="")),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-starts_at", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["is_published", "starts_at"], name="events_even_is_publ_e8a6f1_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["slug"], name="events_even_slug_27c0b5_idx"),
        ),
    ]

