# Generated by Django 6.0.4 on 2026-05-02 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='event',
            new_name='events_even_is_publ_415ff6_idx',
            old_name='events_even_is_publ_e8a6f1_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='events_even_slug_30eb0f_idx',
            old_name='events_even_slug_27c0b5_idx',
        ),
    ]
