# Generated by Django 6.0.4 on 2026-05-02 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_events_even_is_publ_e8a6f1_idx_events_even_is_publ_415ff6_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-starts_at', '-created_at'], 'verbose_name': 'Etkinlik', 'verbose_name_plural': 'Etkinlikler'},
        ),
    ]
