# Generated by Django 6.0.4 on 2026-05-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_meta_verbose_tr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cover_image_url',
            field=models.URLField(blank=True, default='', verbose_name='Kapak URL'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bitiş'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Yayında'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, default='', max_length=180, verbose_name='Konum'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Kısa ad (slug)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Başlangıç'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Başlık'),
        ),
    ]
