# Generated by Django 6.0.4 on 2026-04-29 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('basic', 'Temel'), ('pro', 'Pro'), ('enterprise', 'Kurumsal')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('price_try', models.PositiveIntegerField(help_text='Aylık ücret (₺) - gösterim amaçlı.')),
                ('is_active', models.BooleanField(default=True)),
                ('stripe_price_id', models.CharField(blank=True, default='', max_length=120)),
                ('iyzico_plan_reference', models.CharField(blank=True, default='', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('iyzico', 'iyzico'), ('manual', 'Manuel')], default='manual', max_length=20)),
                ('provider_customer_id', models.CharField(blank=True, default='', max_length=120)),
                ('provider_subscription_id', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('incomplete', 'Eksik'), ('past_due', 'Ödeme Gecikmiş'), ('canceled', 'İptal'), ('expired', 'Süresi Doldu')], default='incomplete', max_length=20)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionplan')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='subscriptio_user_id_2a19e8_idx'), models.Index(fields=['provider', 'provider_subscription_id'], name='subscriptio_provide_686470_idx')],
            },
        ),
    ]
