# Generated by Django 6.0.4 on 2026-05-02 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscriptionplan_billing_cycle_days'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-created_at'], 'verbose_name': 'Abonelik', 'verbose_name_plural': 'Abonelikler'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'verbose_name': 'Abonelik planı', 'verbose_name_plural': 'Abonelik planları'},
        ),
    ]
