# Generated by Django 6.0.4 on 2026-05-02 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_meta_verbose_tr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False, help_text='İşaretliyse süre dolunca yenilenmez.', verbose_name='Dönem sonunda iptal'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='current_period_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dönem bitişi'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='current_period_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dönem başlangıcı'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionplan', verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('iyzico', 'iyzico'), ('manual', 'Manuel')], default='manual', help_text='Aboneliği hangi sağlayıcının yönettiği.', max_length=20, verbose_name='Ödeme sağlayıcısı'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='provider_customer_id',
            field=models.CharField(blank=True, default='', help_text='Örn. Stripe customer id.', max_length=120, verbose_name='Müşteri kimliği (sağlayıcı)'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='provider_subscription_id',
            field=models.CharField(blank=True, default='', help_text='Webhook ve iptal işlemlerinde gereken dış kimlik.', max_length=120, verbose_name='Abonelik kimliği (sağlayıcı)'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Aktif'), ('incomplete', 'Eksik'), ('past_due', 'Ödeme Gecikmiş'), ('canceled', 'İptal'), ('expired', 'Süresi Doldu')], default='incomplete', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='billing_cycle_days',
            field=models.PositiveSmallIntegerField(default=30, help_text='Tek sefer ödeme ile dönem uzunluğu (örn. 30 gün erişim).', verbose_name='Faturalama döngüsü (gün)'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='code',
            field=models.CharField(choices=[('basic', 'Temel'), ('pro', 'Pro'), ('enterprise', 'Kurumsal')], help_text='Sistem içi benzersiz kısa kod (stripe/iyzico eşlemesi için).', max_length=20, unique=True, verbose_name='Plan kodu'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Pasif planlar seçim ekranında çıkmaz.', verbose_name='Aktif satış'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='iyzico_plan_reference',
            field=models.CharField(blank=True, default='', help_text='İyzico tekrarlı ödemeler için iç referans kodu.', max_length=120, verbose_name='İyzico plan referansı'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price_try',
            field=models.PositiveIntegerField(help_text='Aylık veya dönem fiyat gösterimi için tam sayı tutar.', verbose_name='Liste fiyatı (₺)'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='stripe_price_id',
            field=models.CharField(blank=True, default='', help_text='Stripe Dashboard’dan kopyalanan price id.', max_length=120, verbose_name='Stripe Price ID'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Görünen ad'),
        ),
    ]
