# Generated by Django 6.0.4 on 2026-05-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_alter_subscription_cancel_at_period_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deneme bitişi'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='trial_days',
            field=models.PositiveSmallIntegerField(default=7, help_text='İlk kayıt için ücretsiz deneme süresi (gün).', verbose_name='Ücretsiz deneme (gün)'),
        ),
    ]
