# Generated by Django 6.0.4 on 2026-05-17 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_subscription_trial_ends_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Paket adı')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='Kısa ad')),
                ('description', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('price_try', models.PositiveIntegerField(default=0, verbose_name='Aylık fiyat (₺)')),
                ('billing_cycle_days', models.PositiveSmallIntegerField(default=30, verbose_name='Dönem (gün)')),
                ('includes_premium_courses', models.BooleanField(default=True, help_text='Pro/Enterprise erişim seviyeli kurslar.', verbose_name='Premium kurslar')),
                ('includes_all_exams', models.BooleanField(default=True, verbose_name='Tüm deneme sınavları')),
                ('includes_marketplace', models.BooleanField(default=False, verbose_name='Mağaza indirimleri')),
                ('is_active', models.BooleanField(default=True, verbose_name='Satışta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('owner', models.ForeignKey(help_text='Genelde öğretmen veya kurum yöneticisi.', on_delete=django.db.models.deletion.CASCADE, related_name='institution_packages', to=settings.AUTH_USER_MODEL, verbose_name='Paket sahibi')),
            ],
            options={
                'verbose_name': 'Kurum paketi',
                'verbose_name_plural': 'Kurum paketleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentPackageSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('incomplete', 'Eksik'), ('past_due', 'Ödeme Gecikmiş'), ('canceled', 'İptal'), ('expired', 'Süresi Doldu')], default='active', max_length=20, verbose_name='Durum')),
                ('current_period_end', models.DateTimeField(blank=True, null=True, verbose_name='Dönem bitişi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.institutionpackage', verbose_name='Paket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_package_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Öğrenci')),
            ],
            options={
                'verbose_name': 'Öğrenci paket aboneliği',
                'verbose_name_plural': 'Öğrenci paket abonelikleri',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='subscriptio_user_id_f5c6ff_idx')],
            },
        ),
    ]
