# Generated by Django 6.0.4 on 2026-05-02 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_newslettersubscriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'İletişim mesajı', 'verbose_name_plural': 'İletişim mesajları'},
        ),
        migrations.AlterModelOptions(
            name='newslettersubscriber',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bülten abonesi', 'verbose_name_plural': 'Bülten aboneleri'},
        ),
    ]
