# Generated by Django 6.0.4 on 2026-05-02 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='blogpost',
            new_name='blog_blogpo_is_publ_dcd2a8_idx',
            old_name='blog_blogpo_is_publ_4eebdc_idx',
        ),
        migrations.RenameIndex(
            model_name='blogpost',
            new_name='blog_blogpo_slug_361555_idx',
            old_name='blog_blogpo_slug_b0fc19_idx',
        ),
    ]
