# Generated by Django 6.0.4 on 2026-05-02 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_blog_blogpo_is_publ_4eebdc_idx_blog_blogpo_is_publ_dcd2a8_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-published_at', '-created_at'], 'verbose_name': 'Blog yazısı', 'verbose_name_plural': 'Blog yazıları'},
        ),
    ]
