# Generated by Django 6.0.4 on 2026-05-02 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='lessonprogress',
            new_name='progress_le_user_id_48aa73_idx',
            old_name='progress_le_user_id_65c0b5_idx',
        ),
    ]
