# Generated by Django 6.0.4 on 2026-05-02 21:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_uniq_constraints_and_meta'),
        ('progress', '0002_rename_progress_le_user_id_65c0b5_idx_progress_le_user_id_48aa73_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonprogress',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Ders ilerlemesi', 'verbose_name_plural': 'Ders ilerlemeleri'},
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='lessonprogress',
            constraint=models.UniqueConstraint(fields=('user', 'lesson'), name='progress_lessonprogress_user_lesson_uniq'),
        ),
    ]
