# Generated by Django 6.0.4 on 2026-05-02 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_alter_course_access_level_and_more'),
        ('progress', '0003_uniq_constraints_and_meta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonprogress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='İlk kayıt'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Öğrenci ders sonuna geldi olarak işaretledi.', verbose_name='Tamamlandı'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_rows', to='lessons.lesson', verbose_name='Ders'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='progress_percent',
            field=models.PositiveSmallIntegerField(default=0, help_text='0–100 arası ilerleme göstergesi.', verbose_name='Tamamlama yüzdesi'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Son güncelleme'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL, verbose_name='Öğrenci'),
        ),
    ]
