# Generated by Django 6.0.4 on 2026-05-17 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('exam_type', models.CharField(choices=[('lgs', 'LGS'), ('yks', 'YKS'), ('ales', 'ALES'), ('custom', 'Özel')], default='custom', max_length=20, verbose_name='Sınav türü')),
                ('description', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('duration_minutes', models.PositiveIntegerField(default=120, help_text='Sayaç sunucuda biter; tarayıcı kapansa da süre işler.', verbose_name='Süre (dakika)')),
                ('negative_per_wrong', models.DecimalField(decimal_places=2, default=0.25, help_text='LGS/YKS için genelde 0,25; ALES farklı olabilir.', max_digits=4, verbose_name='Yanlış başına düşülen net')),
                ('is_published', models.BooleanField(default=False, verbose_name='Yayında')),
                ('show_leaderboard', models.BooleanField(default=True, help_text='Kurum / Türkiye geneli sıralama listesinde göster.', verbose_name='Sıralama tablosu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exams', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Deneme sınavı',
                'verbose_name_plural': 'Deneme sınavları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'Devam ediyor'), ('submitted', 'Gönderildi'), ('expired', 'Süre doldu')], default='in_progress', max_length=20, verbose_name='Durum')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Başlangıç')),
                ('ends_at', models.DateTimeField(help_text='Süre bu zamanda dolar.', verbose_name='Bitiş (sunucu)')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Gönderim')),
                ('correct_count', models.PositiveIntegerField(default=0, verbose_name='Doğru')),
                ('wrong_count', models.PositiveIntegerField(default=0, verbose_name='Yanlış')),
                ('blank_count', models.PositiveIntegerField(default=0, verbose_name='Boş')),
                ('net_score', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Net')),
                ('analysis_summary', models.TextField(blank=True, default='', help_text='Konu bazlı otomatik yorum.', verbose_name='Analiz özeti')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exams.exam', verbose_name='Sınav')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Öğrenci')),
            ],
            options={
                'verbose_name': 'Sınav oturumu',
                'verbose_name_plural': 'Sınav oturumları',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('topic_slug', models.SlugField(blank=True, default='', max_length=80, verbose_name='Konu kodu')),
                ('topic_title', models.CharField(blank=True, default='', max_length=160, verbose_name='Konu adı')),
                ('correct_choice', models.CharField(help_text='A, B, C, D veya E', max_length=1, verbose_name='Doğru şık')),
                ('choice_count', models.PositiveSmallIntegerField(default=5, verbose_name='Şık sayısı')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam', verbose_name='Sınav')),
            ],
            options={
                'verbose_name': 'Sınav sorusu',
                'verbose_name_plural': 'Sınav soruları',
                'ordering': ['order_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(blank=True, default='', help_text='Boş bırakıldıysa boş string.', max_length=1, verbose_name='İşaretlenen şık')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.examattempt', verbose_name='Oturum')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.examquestion', verbose_name='Soru')),
            ],
            options={
                'verbose_name': 'Cevap',
                'verbose_name_plural': 'Cevaplar',
            },
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['exam', 'status', 'net_score'], name='exams_exama_exam_id_043490_idx'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['user', 'exam'], name='exams_exama_user_id_574733_idx'),
        ),
        migrations.AddConstraint(
            model_name='examanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='exams_examanswer_attempt_question_uniq'),
        ),
    ]
