# Generated by Django 6.0.4 on 2026-05-02 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='coursereview',
            new_name='reviews_cou_course__42800b_idx',
            old_name='reviews_co_course__fdf5ff_idx',
        ),
        migrations.RenameIndex(
            model_name='coursereview',
            new_name='reviews_cou_course__1bc0ab_idx',
            old_name='reviews_co_course__8e3738_idx',
        ),
    ]
