# Generated by Django 6.0.4 on 2026-05-02 21:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_uniq_constraints_and_meta'),
        ('reviews', '0002_rename_reviews_co_course__fdf5ff_idx_reviews_cou_course__42800b_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursereview',
            options={'ordering': ['-created_at'], 'verbose_name': 'Kurs değerlendirmesi', 'verbose_name_plural': 'Kurs değerlendirmeleri'},
        ),
        migrations.AlterUniqueTogether(
            name='coursereview',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='coursereview',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='reviews_coursereview_user_course_uniq'),
        ),
    ]
