# Generated by Django 6.0.4 on 2026-05-02 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_alter_course_access_level_and_more'),
        ('reviews', '0003_uniq_constraints_and_meta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursereview',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Yorum'),
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='lessons.course', verbose_name='Kurs'),
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma'),
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='rating',
            field=models.PositiveSmallIntegerField(help_text='1 (en düşük) ile 5 (en yüksek) arasında tam sayı.', verbose_name='Puan'),
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme'),
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
    ]
