# Generated by Django 6.0.4 on 2026-05-17 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='Son teslim')),
                ('status', models.CharField(choices=[('open', 'Açık'), ('closed', 'Kapalı')], default='open', max_length=20, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to=settings.AUTH_USER_MODEL, verbose_name='Öğretmen')),
            ],
            options={
                'verbose_name': 'Ödev',
                'verbose_name_plural': 'Ödevler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(help_text='Öğrencinin çektiği ödev görseli (JPG/PNG/PDF).', upload_to='homework/%Y/%m/', verbose_name='Ödev fotoğrafı')),
                ('note', models.TextField(blank=True, default='', verbose_name='Öğrenci notu')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('reviewed', 'İncelendi'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], default='pending', max_length=20, verbose_name='Durum')),
                ('teacher_feedback', models.TextField(blank=True, default='', verbose_name='Öğretmen geri bildirimi')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Yükleme')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.homework', verbose_name='Ödev')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Öğrenci')),
            ],
            options={
                'verbose_name': 'Ödev teslimi',
                'verbose_name_plural': 'Ödev teslimleri',
                'ordering': ['-submitted_at'],
                'constraints': [models.UniqueConstraint(fields=('homework', 'student'), name='assignments_homeworksubmission_homework_student_uniq')],
            },
        ),
    ]
