# Generated by Django 6.0.4 on 2026-05-02 21:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_seller_payout_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['-created_at'], 'verbose_name': 'Materyal', 'verbose_name_plural': 'Materyaller'},
        ),
        migrations.AlterModelOptions(
            name='materialaccess',
            options={'verbose_name': 'Materyal erişimi', 'verbose_name_plural': 'Materyal erişimleri'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Sipariş', 'verbose_name_plural': 'Siparişler'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Sipariş kalemi', 'verbose_name_plural': 'Sipariş kalemleri'},
        ),
        migrations.AlterModelOptions(
            name='sellerearning',
            options={'ordering': ['-created_at'], 'verbose_name': 'Satıcı hakedişi', 'verbose_name_plural': 'Satıcı hakedişleri'},
        ),
        migrations.AlterModelOptions(
            name='sellerpayout',
            options={'ordering': ['-paid_at'], 'verbose_name': 'Satıcı ödemesi', 'verbose_name_plural': 'Satıcı ödemeleri'},
        ),
        migrations.AlterUniqueTogether(
            name='materialaccess',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='materialaccess',
            constraint=models.UniqueConstraint(fields=('material', 'user'), name='marketplace_materialaccess_material_user_uniq'),
        ),
    ]
