# Generated by Django 6.0.4 on 2026-05-02 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_uniq_constraints_and_meta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma'),
        ),
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Liste ve detay sayfasında görünen kısa açıklama.', verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(help_text='Satın alma sonrası indirilecek asıl dosya.', upload_to='materials/%Y/%m/', verbose_name='Dosya'),
        ),
        migrations.AlterField(
            model_name='material',
            name='is_published',
            field=models.BooleanField(default=False, help_text='İşaretli değilse mağazada görünmez.', verbose_name='Yayında'),
        ),
        migrations.AlterField(
            model_name='material',
            name='price_try',
            field=models.PositiveIntegerField(default=0, help_text='Türk Lirası cinsinden tam sayı tutar.', verbose_name='Fiyat (₺)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='seller',
            field=models.ForeignKey(help_text='Materyali yayımlayan kullanıcı (genelde öğretmen).', on_delete=django.db.models.deletion.CASCADE, related_name='materials', to=settings.AUTH_USER_MODEL, verbose_name='Satıcı'),
        ),
        migrations.AlterField(
            model_name='material',
            name='title',
            field=models.CharField(max_length=160, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='material',
            name='type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('video', 'Video'), ('other', 'Diğer')], default='pdf', help_text='Dosya içerik tipi (PDF, video vb.).', max_length=20, verbose_name='Tür'),
        ),
        migrations.AlterField(
            model_name='materialaccess',
            name='granted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Verilme zamanı'),
        ),
        migrations.AlterField(
            model_name='materialaccess',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='marketplace.material', verbose_name='Materyal'),
        ),
        migrations.AlterField(
            model_name='materialaccess',
            name='user',
            field=models.ForeignKey(help_text='Erişim verilen alıcı veya tanımlanan kullanıcı.', on_delete=django.db.models.deletion.CASCADE, related_name='material_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(help_text='Siparişi veren kullanıcı.', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Alıcı'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma'),
        ),
        migrations.AlterField(
            model_name='order',
            name='provider',
            field=models.CharField(default='', help_text='Örn. stripe veya iyzico — webhook ve mutabakat için.', max_length=20, verbose_name='Ödeme sağlayıcısı'),
        ),
        migrations.AlterField(
            model_name='order',
            name='provider_payment_id',
            field=models.CharField(blank=True, default='', help_text='Ödeme sağlayıcısından dönen benzersiz işlem kodu.', max_length=120, verbose_name='Sağlayıcı ödeme kimliği'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Beklemede'), ('paid', 'Ödendi'), ('refunded', 'İade'), ('canceled', 'İptal')], default='pending', help_text='Ödeme ve teslim sürecinin anlık durumu.', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_try',
            field=models.PositiveIntegerField(default=0, help_text='Siparişteki kalemlerin toplamı (Türk Lirası, tam sayı).', verbose_name='Toplam (₺)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='marketplace.material', verbose_name='Materyal'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marketplace.order', verbose_name='Sipariş'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price_try',
            field=models.PositiveIntegerField(help_text='Satır bazında materyalin o anki Türk Lirası fiyatı.', verbose_name='Birim fiyat (₺)'),
        ),
        migrations.AlterField(
            model_name='sellerearning',
            name='commission_try',
            field=models.PositiveIntegerField(help_text='Platform payı olarak kesilen Türk Lirası tutarı.', verbose_name='Komisyon (₺)'),
        ),
        migrations.AlterField(
            model_name='sellerearning',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Kayıt zamanı'),
        ),
        migrations.AlterField(
            model_name='sellerearning',
            name='gross_try',
            field=models.PositiveIntegerField(help_text='Satış tutarı, komisyon düşülmeden önce.', verbose_name='Brüt (₺)'),
        ),
        migrations.AlterField(
            model_name='sellerearning',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seller_earnings', to='marketplace.material', verbose_name='Materyal'),
        ),
        migrations.AlterField(
            model_name='sellerearning',
            name='net_try',
            field=models.PositiveIntegerField(help_text='Satıcıya düşecek Türk Lirası tutarı (brüt − komisyon).', verbose_name='Net (₺)'),
        ),
        migrations.AlterField(
            model_name='sellerearning',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_earnings', to='marketplace.order', verbose_name='Sipariş'),
        ),
        migrations.AlterField(
            model_name='sellerearning',
            name='payout',
            field=models.ForeignKey(blank=True, help_text='Bu hakedişin hangi toplu ödemeye dahil olduğu.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earnings', to='marketplace.sellerpayout', verbose_name='Ödeme kaydı'),
        ),
        migrations.AlterField(
            model_name='sellerearning',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_earnings', to=settings.AUTH_USER_MODEL, verbose_name='Satıcı'),
        ),
        migrations.AlterField(
            model_name='sellerpayout',
            name='paid_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ödeme tarihi'),
        ),
        migrations.AlterField(
            model_name='sellerpayout',
            name='reference_note',
            field=models.TextField(blank=True, default='', help_text='Dekont no, havale açıklaması veya iç not.', verbose_name='Referans notu'),
        ),
        migrations.AlterField(
            model_name='sellerpayout',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_payouts', to=settings.AUTH_USER_MODEL, verbose_name='Satıcı'),
        ),
        migrations.AlterField(
            model_name='sellerpayout',
            name='total_net_try',
            field=models.PositiveIntegerField(default=0, help_text='Bu ödemede kullanıcıya iletilen toplam net tutar.', verbose_name='Toplam net (₺)'),
        ),
    ]
