# Generated by Django 6.0.4 on 2026-04-30 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lessons", "0001_initial"),
        ("marketplace", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseWishlist",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("course", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="wishlisted_by", to="lessons.course")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="course_wishlist_items", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"], "unique_together": {("user", "course")}},
        ),
        migrations.CreateModel(
            name="MaterialWishlist",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("material", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="wishlisted_by", to="marketplace.material")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="material_wishlist_items", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"], "unique_together": {("user", "material")}},
        ),
        migrations.AddIndex(
            model_name="coursewishlist",
            index=models.Index(fields=["user", "created_at"], name="wishlist_co_user_id_1ecb7c_idx"),
        ),
        migrations.AddIndex(
            model_name="materialwishlist",
            index=models.Index(fields=["user", "created_at"], name="wishlist_ma_user_id_2e1de6_idx"),
        ),
    ]

