# Generated by Django 6.0.4 on 2026-05-02 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='coursewishlist',
            new_name='wishlist_co_user_id_a30378_idx',
            old_name='wishlist_co_user_id_1ecb7c_idx',
        ),
        migrations.RenameIndex(
            model_name='materialwishlist',
            new_name='wishlist_ma_user_id_1e4707_idx',
            old_name='wishlist_ma_user_id_2e1de6_idx',
        ),
    ]
