# Generated by Django 6.0.4 on 2026-05-02 21:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_uniq_constraints_and_meta'),
        ('marketplace', '0003_uniq_constraints_and_meta'),
        ('wishlist', '0002_rename_wishlist_co_user_id_1ecb7c_idx_wishlist_co_user_id_a30378_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursewishlist',
            options={'ordering': ['-created_at'], 'verbose_name': 'Kurs istek kaydı', 'verbose_name_plural': 'Kurs istek kayıtları'},
        ),
        migrations.AlterModelOptions(
            name='materialwishlist',
            options={'ordering': ['-created_at'], 'verbose_name': 'Materyal istek kaydı', 'verbose_name_plural': 'Materyal istek kayıtları'},
        ),
        migrations.AlterUniqueTogether(
            name='coursewishlist',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='materialwishlist',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='coursewishlist',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='wishlist_course_user_course_uniq'),
        ),
        migrations.AddConstraint(
            model_name='materialwishlist',
            constraint=models.UniqueConstraint(fields=('user', 'material'), name='wishlist_material_user_material_uniq'),
        ),
    ]
