# Generated by Django 6.0.4 on 2026-05-02 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_alter_course_access_level_and_more'),
        ('marketplace', '0004_alter_material_created_at_alter_material_description_and_more'),
        ('wishlist', '0003_uniq_constraints_and_meta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursewishlist',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='lessons.course', verbose_name='Kurs'),
        ),
        migrations.AlterField(
            model_name='coursewishlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Eklenme zamanı'),
        ),
        migrations.AlterField(
            model_name='coursewishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_wishlist_items', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='materialwishlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Eklenme zamanı'),
        ),
        migrations.AlterField(
            model_name='materialwishlist',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='marketplace.material', verbose_name='Materyal'),
        ),
        migrations.AlterField(
            model_name='materialwishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_wishlist_items', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
    ]
