# Generated by Django 6.0.4 on 2026-05-02 21:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-starts_at'], 'verbose_name': 'Randevu', 'verbose_name_plural': 'Randevular'},
        ),
        migrations.AlterModelOptions(
            name='teacheravailability',
            options={'ordering': ['weekday', 'start_time'], 'verbose_name': 'Öğretmen müsaitliği', 'verbose_name_plural': 'Öğretmen müsaitlikleri'},
        ),
        migrations.AlterUniqueTogether(
            name='teacheravailability',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='teacheravailability',
            constraint=models.UniqueConstraint(fields=('teacher', 'weekday', 'start_time', 'end_time'), name='booking_teacheravail_teacher_weekday_slot_uniq'),
        ),
    ]
