# Generated by Django 6.0.4 on 2026-05-02 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_uniq_constraints_and_meta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='ends_at',
            field=models.DateTimeField(verbose_name='Bitiş'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='note',
            field=models.CharField(blank=True, default='', help_text='Tarafların görebileceği kısa açıklama.', max_length=500, verbose_name='Not'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='starts_at',
            field=models.DateTimeField(verbose_name='Başlangıç'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Beklemede'), ('confirmed', 'Onaylandı'), ('canceled', 'İptal'), ('completed', 'Tamamlandı')], default='pending', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Öğrenci'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Öğretmen'),
        ),
        migrations.AlterField(
            model_name='teacheravailability',
            name='end_time',
            field=models.TimeField(verbose_name='Bitiş saati'),
        ),
        migrations.AlterField(
            model_name='teacheravailability',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Pasif bloklar öğrenciye gösterilmez.', verbose_name='Aktif'),
        ),
        migrations.AlterField(
            model_name='teacheravailability',
            name='start_time',
            field=models.TimeField(verbose_name='Başlangıç saati'),
        ),
        migrations.AlterField(
            model_name='teacheravailability',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to=settings.AUTH_USER_MODEL, verbose_name='Öğretmen'),
        ),
        migrations.AlterField(
            model_name='teacheravailability',
            name='weekday',
            field=models.IntegerField(choices=[(1, 'Pazartesi'), (2, 'Salı'), (3, 'Çarşamba'), (4, 'Perşembe'), (5, 'Cuma'), (6, 'Cumartesi'), (7, 'Pazar')], verbose_name='Haftanın günü'),
        ),
    ]
