# Generated by Django 6.0.4 on 2026-05-02 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communityanswer',
            options={'ordering': ['created_at'], 'verbose_name': 'Topluluk yanıtı', 'verbose_name_plural': 'Topluluk yanıtları'},
        ),
        migrations.AlterModelOptions(
            name='communitycategory',
            options={'ordering': ['title'], 'verbose_name': 'Topluluk kategorisi', 'verbose_name_plural': 'Topluluk kategorileri'},
        ),
        migrations.AlterModelOptions(
            name='communitypost',
            options={'ordering': ['-created_at'], 'verbose_name': 'Topluluk gönderisi', 'verbose_name_plural': 'Topluluk gönderileri'},
        ),
    ]
