# Generated by Django 6.0.4 on 2026-05-02 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_meta_verbose_tr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityanswer',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Onay zamanı'),
        ),
        migrations.AlterField(
            model_name='communityanswer',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_answers', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan'),
        ),
        migrations.AlterField(
            model_name='communityanswer',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_answers', to=settings.AUTH_USER_MODEL, verbose_name='Yazar'),
        ),
        migrations.AlterField(
            model_name='communityanswer',
            name='body',
            field=models.TextField(verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='communityanswer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma'),
        ),
        migrations.AlterField(
            model_name='communityanswer',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='community.communitypost', verbose_name='Gönderi'),
        ),
        migrations.AlterField(
            model_name='communityanswer',
            name='status',
            field=models.CharField(choices=[('pending', 'Beklemede'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], default='pending', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='communitycategory',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='communitycategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif'),
        ),
        migrations.AlterField(
            model_name='communitycategory',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Kısa ad (slug)'),
        ),
        migrations.AlterField(
            model_name='communitycategory',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Onay zamanı'),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_posts', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan'),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to=settings.AUTH_USER_MODEL, verbose_name='Yazar'),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='body',
            field=models.TextField(verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='community.communitycategory', verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma'),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='status',
            field=models.CharField(choices=[('pending', 'Beklemede'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], default='pending', help_text='Moderasyon sonrası yayına alınır.', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='title',
            field=models.CharField(max_length=180, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='type',
            field=models.CharField(choices=[('question', 'Soru'), ('update', 'Güncelleme'), ('event', 'Etkinlik')], default='question', max_length=20, verbose_name='Tür'),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme'),
        ),
    ]
